import type { KickBadge, KickChatMessage, KickUserIdentity } from "@/types/kick";

/**
 * Timestamped chat dataset for the replay engine (T4).
 * Messages are keyed to the stream clock via `offset_seconds`; the replay
 * engine reveals each message when the clock passes its offset.
 *
 * The full dataset (70k real messages captured from the same stream as the
 * T3 video, plus injected KickBot gift lines) lives in
 * `public/chat-replay.json`, generated by `scripts/build-chat-replay.mjs`
 * and gitignored like the VOD. loadChatReplay() fetches it once and enriches
 * each row with a deterministic Kick-style identity — the capture carries no
 * colors/badges. If the file hasn't been generated, the seeded messages
 * below are tiled across the stream so chat still flows.
 */

const STREAM_START = Date.parse("2026-08-01T12:00:00Z");

/** Build an ISO timestamp `offset` seconds after the mock stream start. */
function at(offset: number): string {
  return new Date(STREAM_START + offset * 1000).toISOString();
}

export const mockChatMessages: KickChatMessage[] = [
  {
    message_id: "msg-001",
    username: "Trisha82",
    content: "😂 😂",
    timestamp: at(8),
    offset_seconds: 8,
    identity: {
      username_color: "#ff75c8",
      badges: [
        { type: "subscriber", text: "Subscriber", count: 20 },
        { type: "sub_gifter", text: "Sub Gifter", count: 50 },
      ],
    },
  },
  {
    message_id: "msg-002",
    username: "Trisha82",
    content: "😂",
    timestamp: at(14),
    offset_seconds: 14,
    identity: {
      username_color: "#ff75c8",
      badges: [
        { type: "subscriber", text: "Subscriber", count: 20 },
        { type: "sub_gifter", text: "Sub Gifter", count: 50 },
      ],
    },
  },
  {
    message_id: "msg-003",
    username: "Yernutmydad",
    content: "😂 😂 😂",
    timestamp: at(21),
    offset_seconds: 21,
    identity: { username_color: "#e9c46a", badges: [] },
  },
  {
    message_id: "msg-004",
    username: "Deuces_tm",
    content: "now now, just because you got a real money tip doesn't mean it's fake",
    timestamp: at(30),
    offset_seconds: 30,
    identity: {
      username_color: "#31c4f3",
      badges: [{ type: "sub_gifter", text: "Sub Gifter", count: 5 }],
    },
  },
  {
    message_id: "msg-005",
    username: "BahRykz",
    content: ", ml",
    timestamp: at(37),
    offset_seconds: 37,
    identity: {
      username_color: "#f3d02f",
      badges: [{ type: "subscriber", text: "Subscriber", count: 14 }],
    },
  },
  {
    message_id: "msg-006",
    username: "Deuces_tm",
    content: "I will always believe it's fake",
    timestamp: at(45),
    offset_seconds: 45,
    identity: {
      username_color: "#31c4f3",
      badges: [{ type: "sub_gifter", text: "Sub Gifter", count: 5 }],
    },
  },
  {
    message_id: "msg-007",
    username: "KickBot",
    content: "@DamaniStrange just gifted 100 KICKs!",
    timestamp: at(52),
    offset_seconds: 52,
    identity: { username_color: "#53fc18", badges: [{ type: "bot", text: "Bot" }] },
  },
  {
    message_id: "msg-008",
    username: "Xsarahannx",
    content: "🐱",
    timestamp: at(60),
    offset_seconds: 60,
    identity: {
      username_color: "#a970ff",
      badges: [{ type: "subscriber", text: "Subscriber", count: 1 }],
    },
  },
  {
    message_id: "msg-009",
    username: "BahRykz",
    content: "#,,",
    timestamp: at(66),
    offset_seconds: 66,
    identity: {
      username_color: "#f3d02f",
      badges: [{ type: "subscriber", text: "Subscriber", count: 14 }],
    },
  },
  {
    message_id: "msg-010",
    username: "TheBrotherRik",
    content: "Chur brother i didn't see who it was my chat freezes all the time 🙃",
    timestamp: at(74),
    offset_seconds: 74,
    identity: {
      username_color: "#4ade80",
      badges: [
        { type: "subscriber", text: "Subscriber", count: 23 },
        { type: "sub_gifter", text: "Sub Gifter", count: 10 },
      ],
    },
  },
  {
    message_id: "msg-011",
    username: "Deuces_tm",
    content: "I looked at the job, said yup time for a smoke and a coffee",
    timestamp: at(83),
    offset_seconds: 83,
    identity: {
      username_color: "#31c4f3",
      badges: [{ type: "sub_gifter", text: "Sub Gifter", count: 5 }],
    },
  },
  {
    message_id: "msg-012",
    username: "DamaniStrange",
    content: "50 followers",
    timestamp: at(90),
    offset_seconds: 90,
    identity: { username_color: "#f97316", badges: [] },
  },
  {
    message_id: "msg-013",
    username: "mu1ishatr00p",
    content: "LETS GO DOC 🔥",
    timestamp: at(97),
    offset_seconds: 97,
    identity: {
      username_color: "#38bdf8",
      badges: [{ type: "subscriber", text: "Subscriber", count: 5 }],
    },
  },
  {
    message_id: "msg-014",
    username: "Catto095",
    content: "W",
    timestamp: at(103),
    offset_seconds: 103,
    identity: {
      username_color: "#fb7185",
      badges: [{ type: "subscriber", text: "Subscriber", count: 1 }],
    },
  },
];

/** Row shape in `public/chat-replay.json`. */
export type ChatReplayRow = [offsetSeconds: number, username: string, content: string];

/** Kick-style username palette — vivid, readable on the dark theme. */
const USERNAME_COLORS = [
  "#ff75c8",
  "#e9c46a",
  "#31c4f3",
  "#f3d02f",
  "#a970ff",
  "#4ade80",
  "#f97316",
  "#38bdf8",
  "#fb7185",
  "#c084fc",
  "#34d399",
  "#facc15",
  "#f472b6",
  "#60a5fa",
  "#fb923c",
  "#2dd4bf",
];

/** FNV-1a — stable, so a username keeps its color/badges everywhere. */
function hashUsername(name: string): number {
  let h = 0x811c9dc5;
  for (let i = 0; i < name.length; i++) {
    h ^= name.charCodeAt(i);
    h = Math.imul(h, 0x01000193) >>> 0;
  }
  return h;
}

const identityCache = new Map<string, KickUserIdentity>();

/**
 * Deterministic Kick-style identity for a captured username (the capture has
 * no colors/badges): everyone gets a palette color; roughly a third are
 * subscribers, some also gift subs, a handful are mods.
 */
export function identityFor(username: string): KickUserIdentity {
  const cached = identityCache.get(username);
  if (cached) return cached;

  let identity: KickUserIdentity;
  if (username === "KickBot") {
    identity = {
      username_color: "#53fc18",
      badges: [{ type: "bot", text: "Bot" }],
    };
  } else {
    const h = hashUsername(username);
    const badges: KickBadge[] = [];
    if ((h >>> 20) % 100 < 2) {
      badges.push({ type: "moderator", text: "Moderator" });
    }
    if ((h >>> 4) % 100 < 35) {
      badges.push({
        type: "subscriber",
        text: "Subscriber",
        count: 1 + ((h >>> 8) % 36),
      });
    }
    if ((h >>> 12) % 100 < 8) {
      badges.push({
        type: "sub_gifter",
        text: "Sub Gifter",
        count: [1, 5, 10, 25, 50, 100, 200][(h >>> 16) % 7],
      });
    }
    identity = {
      username_color: USERNAME_COLORS[h % USERNAME_COLORS.length],
      badges,
    };
  }
  identityCache.set(username, identity);
  return identity;
}

function toMessage(
  [offset, username, content]: ChatReplayRow,
  index: number,
): KickChatMessage {
  return {
    message_id: `replay-${index}`,
    username,
    content,
    timestamp: at(offset),
    offset_seconds: offset,
    identity: identityFor(username),
  };
}

/** Enrich raw replay rows into full chat messages — shared by the client
 * loader below and the server-side loader in `src/lib/server/chat-replay.ts`. */
export function replayRowsToMessages(rows: ChatReplayRow[]): KickChatMessage[] {
  return rows.map(toMessage);
}

/** ≈ the VOD length; the fallback dataset covers the same span. */
const FALLBACK_SPAN_SECONDS = 6 * 3600 + 21 * 60;
const FALLBACK_TILE_SECONDS = 110;

/** Tile the seeded messages across the stream so chat flows without the
 * generated dataset (fresh clone without `assets/`). */
export function tiledSeedFallback(): KickChatMessage[] {
  const out: KickChatMessage[] = [];
  for (let tile = 0; tile * FALLBACK_TILE_SECONDS < FALLBACK_SPAN_SECONDS; tile++) {
    for (const message of mockChatMessages) {
      const offset =
        tile * FALLBACK_TILE_SECONDS + (message.offset_seconds ?? 0);
      out.push({
        ...message,
        message_id: `${message.message_id}-t${tile}`,
        timestamp: at(offset),
        offset_seconds: offset,
      });
    }
  }
  return out;
}

let replayPromise: Promise<KickChatMessage[]> | null = null;

/**
 * The full replay dataset, sorted by offset_seconds. Fetched and enriched
 * once per page — the viewer and creator ChatPanels share the same promise.
 */
export function loadChatReplay(): Promise<KickChatMessage[]> {
  replayPromise ??= fetch("/chat-replay.json")
    .then((res) => {
      if (!res.ok) throw new Error(`chat-replay.json: HTTP ${res.status}`);
      return res.json() as Promise<ChatReplayRow[]>;
    })
    .then((rows) => replayRowsToMessages(rows))
    .catch((error: unknown) => {
      console.warn(
        "Chat replay dataset missing — using the looped seed fallback.",
        "Regenerate it with: node scripts/build-chat-replay.mjs",
        error,
      );
      return tiledSeedFallback();
    });
  return replayPromise;
}
